tools:
    external_code_coverage: true
checks:
    php:
        code_rating: true
        duplication: true
   javascript:
        code_rating: false
        duplication: false
filter:
    paths:
        - src/*
build:
    dependencies:
        override:
            - true
